-- Generated by github.com/0990/taberr
-- Version: 0.0.1

local tab = {
	emsg = {
		{ ErrorID = 0, ErrorType = "Invalid", ErrorMsg = "" 	},
		{ ErrorID = 1, ErrorType = "loginfailed", ErrorMsg = "登录失败" 	},
		{ ErrorID = 2, ErrorType = "systemfailed", ErrorMsg = "系统失败" 	}
	}

}


-- ErrorID
tab.emsgByErrorID = {}
for _, rec in pairs(tab.emsg) do
	tab.emsgByErrorID[rec.ErrorID] = rec
end

return tab