-- Generated by github.com/0990/taberr
-- Version: 0.0.1

local tab = {
	packageName = {
		{ ErrorType = "Invalid", ErrorMsg = "" 	},
		{ ErrorType = "loginfailed", ErrorMsg = "登录失败" 	},
		{ ErrorType = "systemfailed", ErrorMsg = "系统失败" 	}
	}

}


-- ErrorType
tab.packageNameByErrorType = {}
for _, rec in pairs(tab.packageName) do
	tab.packageNameByErrorType[rec.ErrorType] = rec
end

tab.Enum = {
	enumName = {
		Invalid = 0,
		loginfailed = 1,
		systemfailed = 2,
	},
}

return tab